### ISSUE TITLE
otlptrace panics when array-type resource attributes are used

### ISSUE THREAD

**Issue by axw** [open-telemetry/opentelemetry-go#2220]
### Description

When exporting trace spans associated with a resource that has array-type attributes, otlptrace exporters panic (at least otlptracegrpc, but I think otlptracehttp too).

### Environment

- OS: Linux
- Architecture: x86_64
- Go Version: 1.16.5
- opentelemetry-go version: v1.0.0-RC3

### Steps To Reproduce

1. Run this:

```go
package main

import (
        "context"
        "log"

        "go.opentelemetry.io/otel/attribute"
        "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
        "go.opentelemetry.io/otel/sdk/resource"
        "go.opentelemetry.io/otel/sdk/trace"
)

func main() {
        exporter, err := otlptracegrpc.New(context.Background())
        if err != nil {
                log.Fatal(err)
        }

        tracerProvider := trace.NewTracerProvider(
                trace.WithSyncer(exporter),
                trace.WithResource(
                        resource.NewSchemaless(
                                attribute.StringSlice("string_array", []string{"a", "b"}),
                        ),
                ),
        )

        tracer := tracerProvider.Tracer("test")
        _, span := tracer.Start(context.Background(), "operation")
        span.End()
```

2. Observe panic:

```
$ go run main.go
panic: runtime error: hash of unhashable type []string

goroutine 1 [running]:
type..hash.go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.ilsKey·1(0xc0002df400, 0x0, 0x0)
        <autogenerated>:1 +0x35
go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.Spans(0xc0003702a0, 0x1, 0x1, 0x40fd98, 0x10, 0x907160)
        /home/andrew/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/internal/tracetransform/span.go:57 +0x433
go.opentelemetry.io/otel/exporters/otlp/otlptrace.(*Exporter).ExportSpans(0xc000090960, 0xa72670, 0xc0000240f8, 0xc0003702a0, 0x1, 0x1, 0x0, 0x0)
        /home/andrew/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.0.0-!r!c3/exporter.go:44 +0x45
go.opentelemetry.io/otel/sdk/trace.(*simpleSpanProcessor).OnEnd(0xc00007f3c0, 0xa78918, 0xc000386000)
        /home/andrew/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/simple_span_processor.go:58 +0x142
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000001e00, 0x0, 0x0, 0x0)
        /home/andrew/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c3/trace/span.go:280 +0x2d7
main.main()
        /tmp/otelgopanic/main.go:30 +0x473
exit status 2
```

### Expected behavior

Should not panic.

**Comment by pkwarren** [comment]
When is the next release planned which will include this change? This caused all OTEL tracing to fail in apps we upgraded to 1.0.0-RC3 (using process resource detector which uses slices for command arguments).

**Comment by MrAlias** [comment]
> When is the next release planned which will include this change? This caused all OTEL tracing to fail in apps we upgraded to 1.0.0-RC3 (using process resource detector which uses slices for command arguments).

Monday 2021-09-20.
