### ISSUE TITLE
Panic in `otel` when running tests with `go1.22.0` and `-gcflags=-l`

### ISSUE THREAD

**Issue by nhatthm** [open-telemetry/opentelemetry-go#4898]
### Description

Panic in `otel` when running tests with `go1.22.0` and `-gcflags=-l`. It works when running without `-gcflags=-l`

It also works with `go1.21` without any issues, with and without `-gcflags=-l`

<details>
  <summary>Click to see the output</summary>
  
  ```shell
$ go1.22.0 test -gcflags=-l ./...
	go.nhat.io/otelsql/internal/test/sqlmock		coverage: 0.0% of statements
	go.nhat.io/otelsql/internal/test/oteltest		coverage: 0.0% of statements
	go.nhat.io/otelsql/internal/test/assert		coverage: 0.0% of statements
--- FAIL: TestTxStats (0.00s)
    --- FAIL: TestTxStats/error (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1d pc=0x1026fb074]

goroutine 145 [running]:
testing.tRunner.func1.2({0x1028bcb60, 0x102b95820})
	/sdk/go1.22.0/src/testing/testing.go:1631 +0x2c8
testing.tRunner.func1()
	/sdk/go1.22.0/src/testing/testing.go:1634 +0x47c
panic({0x1028bcb60?, 0x102b95820?})
	/sdk/go1.22.0/src/runtime/panic.go:770 +0x124
go.opentelemetry.io/otel/sdk/metric.(*multierror).append(...)
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/pipeline.go:657
go.opentelemetry.io/otel/sdk/metric.(*inserter[...]).Instrument(0x10293fce0, {{0x1027bfe22, 0x15}, {0x0, 0x0}, 0x3, {0x0, 0x0}, {{0x1027ba836, 0x7}, ...}, ...}, ...)
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/pipeline.go:268 +0x684
go.opentelemetry.io/otel/sdk/metric.resolver[...].HistogramAggregators(0x10293ebe0?, {{0x1027bfe22, 0x15}, {0x0, 0x0}, 0x3, {0x0, 0x0}, {{0x1027ba836, 0x7}, ...}, ...}, ...)
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/pipeline.go:632 +0x2d0
go.opentelemetry.io/otel/sdk/metric.float64InstProvider.histogramAggs({0xc000247668?}, {0x1027bfe22, 0x15}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/meter.go:642 +0x1fc
go.opentelemetry.io/otel/sdk/metric.float64InstProvider.lookupHistogram.func1()
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/meter.go:667 +0x90
go.opentelemetry.io/otel/sdk/metric.(*cacheWithErr[...]).Lookup.func1()
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/cache.go:90 +0x34
go.opentelemetry.io/otel/sdk/metric.(*cache[...]).Lookup(0x10293d700, {{0x1027bfe22, 0x15}, {0x0, 0x0}, 0x3, {0x0, 0x0}, {0x0, 0x0}}, ...)
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/cache.go:44 +0x268
go.opentelemetry.io/otel/sdk/metric.(*cacheWithErr[...]).Lookup(0x10293bd00, {{0x1027bfe22, 0x15}, {0x0, 0x0}, 0x3, {0x0, 0x0}, {0x0, 0x0}}, ...)
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/cache.go:89 +0x100
go.opentelemetry.io/otel/sdk/metric.float64InstProvider.lookupHistogram({0x0?}, {0x1027bfe22, 0x15}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}})
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/meter.go:661 +0x1f8
go.opentelemetry.io/otel/sdk/metric.(*meter).Float64Histogram(0xc0000ba000, {0x1027bfe22, 0x15}, {0x0, 0x0, 0x0?})
	/go/src/github.com/nhatthm/otelsql/vendor/go.opentelemetry.io/otel/sdk/metric/meter.go:248 +0x188
go.nhat.io/otelsql.TestTxStats.func2.1({0x10293bf50, 0xc0000b2120})
	/go/src/github.com/nhatthm/otelsql/transaction_internal_test.go:116 +0xa4
go.nhat.io/otelsql/internal/test/oteltest.(*suite).Run(0xc0000200f0, 0xc000346000, 0xc00008a140)
	/go/src/github.com/nhatthm/otelsql/internal/test/oteltest/suite.go:112 +0xbc
go.nhat.io/otelsql.TestTxStats.func2(0xc000346000)
	/go/src/github.com/nhatthm/otelsql/transaction_internal_test.go:113 +0x150
testing.tRunner(0xc000346000, 0xc00028d1a0)
	/sdk/go1.22.0/src/testing/testing.go:1689 +0x184
created by testing.(*T).Run in goroutine 88
	/sdk/go1.22.0/src/testing/testing.go:1742 +0x5e8
FAIL	go.nhat.io/otelsql	0.228s
ok  	go.nhat.io/otelsql/attribute	1.152s	coverage: 100.0% of statements
FAIL
  ```
</details>

### Environment

- OS: macOS 14.1.2
- Architecture: arm64
- Go Version: 1.22.0
- opentelemetry-go version: 1.23.1

### Steps To Reproduce

1. `go install golang.org/dl/go1.22.0@latest`
2. `go1.22.0 download`
3. `git clone https://github.com/nhatthm/otelsql`
4. `go1.22.0 test -gcflags=-l ./...`

### Expected behavior

I'm not sure what we expect with the new compiler in `go1.22`, should we stop using `-gcflags=-l`?

**Comment by MrAlias** [comment]
What is the panic message you are seeing?

**Comment by MrAlias** [comment]
I'm guessing this has something to do with https://dave.cheney.net/2020/05/02/mid-stack-inlining-in-go

Is there a reason you disable inlining?

**Comment by MrAlias** [comment]
Closing due to lack of response. Please reopen if you are able to provide the information requested above.
