### ISSUE TITLE
RecordBatch panics if creates measurement before InstallNewPipeline

### ISSUE THREAD

**Issue by lufia** [open-telemetry/opentelemetry-go#677]
The code below will panic with `interface conversion: metric.SyncImpl is *internal.syncImpl, not *metric.syncInstrument`.

```go
package main

import (
	"context"
	"log"

	"go.opentelemetry.io/otel/api/global"
	"go.opentelemetry.io/otel/api/metric"
	"go.opentelemetry.io/otel/exporters/metric/stdout"
)

func main() {
	log.SetFlags(0)
	meter := global.MeterProvider().Meter("example/ping")
	counter := metric.Must(meter).NewInt64Counter("example.counter")

	pusher, err := stdout.InstallNewPipeline(stdout.Config{})
	if err != nil {
		log.Fatal(err)
	}
	defer pusher.Stop()

	n := counter.Measurement(1)
	meter.RecordBatch(context.Background(), nil, n)
}
```

Should I keep to install the exporter before creating any instruments?

### environment

- Go: 1.14
- GOOS: darwin
- GOARCH: amd64
- otel: v0.4.3

**Comment by MrAlias** [comment]
Full output reproducing the above error with the same sample program:

```
go run test.go
{"time":"2020-04-29T13:05:12.257716346-07:00","updates":null}
panic: interface conversion: metric.SyncImpl is *internal.syncImpl, not *metric.syncInstrument

goroutine 1 [running]:
go.opentelemetry.io/otel/sdk/metric.(*SDK).RecordBatch(0xc0000b8000, 0x574fc0, 0xc000014110, 0x0, 0x0, 0x0, 0xc00000c260, 0x1, 0x1)
	/home/tyler/go/pkg/mod/go.opentelemetry.io/otel@v0.4.3/sdk/metric/sdk.go:473 +0x192
go.opentelemetry.io/otel/api/metric/registry.(*uniqueInstrumentMeterImpl).RecordBatch(0xc00000c200, 0x574fc0, 0xc000014110, 0x0, 0x0, 0x0, 0xc00000c260, 0x1, 0x1)
	/home/tyler/go/pkg/mod/go.opentelemetry.io/otel@v0.4.3/api/metric/registry/registry.go:58 +0x94
go.opentelemetry.io/otel/api/metric.(*wrappedMeterImpl).RecordBatch(0xc00000c240, 0x574fc0, 0xc000014110, 0x0, 0x0, 0x0, 0xc00000c260, 0x1, 0x1)
	/home/tyler/go/pkg/mod/go.opentelemetry.io/otel@v0.4.3/api/metric/sdkhelpers.go:134 +0x93
go.opentelemetry.io/otel/api/global/internal.(*meter).RecordBatch(0xc0000621e0, 0x574fc0, 0xc000014110, 0x0, 0x0, 0x0, 0xc00000c260, 0x1, 0x1)
	/home/tyler/go/pkg/mod/go.opentelemetry.io/otel@v0.4.3/api/global/internal/meter.go:331 +0xa5
main.main()
	/home/tyler/go/src/test/test.go:24 +0x2ba
exit status 2
```
